---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: gantsign.oh-my-zsh
      users:
        - username: sandeep.jassal1
          oh-my-zsh:
            theme: pygmalion
            plugins:
              - git
              - zsh-autosuggestions
              - zsh-completions
              - zsh-syntax-highlighting
      tags: ['zsh']

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - include: tasks/chef.yml
      tags: ['chef']

    - include: tasks/vim.yml
      when: configure_vim
      tags: ['vim']

    - include: tasks/vscode.yml
      when: configure_vscode
      tags: ['vscode']

    - include: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include: tasks/gpg.yml
      tags: ['gpg']

    - include: tasks/zsh.yml
      tags: ['zsh']

    - include: tasks/aws.yml
      when: configure_aws
      tags: ['aws']

    - include: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
